### ISSUE TITLE
Problems with Composer remove

### ISSUE THREAD

**Issue by evertalbers** [eckinox/bolt-navigation-ui#9]
Admittedly incomplete issue description:

I installed navigation-ui and decided after some trial and error to remove it using `composer remove`. Then I got

```In FrameworkExtension.php line 1353:
                                                                              
  "/Users/evertalbers/Streeff/Navigant/2112-EHB/00-EHB-website/vendor/eckino  
  x/bolt-navigation-ui/translations" defined in translator.paths does not ex  
  ist or is not a directory. 
```
  
  and my local Bolt instance threw an error (I did not copy this error, sorry about that).

**Comment by EmilePerron** [comment]
Hey Evert!

This is due to the configuration file that is added to your project when you install the extension.

I guess Bolt adds them automatically, but doesn't remove them automatically when you uninstall a package (which makes sense in many ways, as it could theoretically contain configurations for your app that you want to keep.

The file in question for the extension is `config/packages/extension_bolt-navigation-ui.yaml` - you can delete it if you're not using the extension anymore :)

**Comment by evertalbers** [comment]
I was going to say "will do" but couldn't find that file - but then I realised that going back in Apple Time Machine had already deleted it 🙃. I guess leaving that yaml file but commenting all lines would have been the best solution, technically.
Thanks!
